export type Track = "A" | "B";
export type Candidate = {
  id: string;
  track: Track;
  company: string;
  title: string;
  href: string;
  source: "LinkedIn MCP" | "公司官网" | "公开招聘平台";
  location: string;
  roleType: string;
  why: string;
  gate: string;
  verdict: "优先审阅" | "条件式" | "暂不建议";
  scannedOn?: string;
};

type CompanyDetail = { listing: string; size: string; commute: string; salary: string };
const companyDetails: Record<string, CompanyDetail> = {
  "Ubie": { listing:"未上市", size:"约 200–300 人", commute:"约 40–50 分钟", salary:"约 ¥8–15M" },
  "JMDC": { listing:"东证 Prime（4483）", size:"约 500 人（单体）", commute:"约 35–45 分钟", salary:"约 ¥8–16M" },
  "HOKUTO": { listing:"未上市", size:"约 80–100 人", commute:"约 40–50 分钟", salary:"约 ¥8–15M" },
  "Mujin": { listing:"未上市", size:"约 300–500 人", commute:"约 45–60 分钟", salary:"约 ¥7–15M" },
  "Woven by Toyota": { listing:"未上市（Toyota 旗下）", size:"约 1,000+ 人", commute:"东京约 30–45 分钟", salary:"约 ¥8–16M" },
  "Rapyuta Robotics": { listing:"未上市", size:"约 100–200 人", commute:"约 45–60 分钟", salary:"约 ¥7–15M" },
  "Prox Industries": { listing:"未上市", size:"早期团队", commute:"待确认", salary:"约 ¥7–13M" },
  "inaho": { listing:"未上市", size:"早期团队", commute:"待确认", salary:"约 ¥6–10M" },
  "MI-6": { listing:"未上市", size:"约 100–200 人", commute:"约 40–55 分钟", salary:"约 ¥7–12M" },
  "Entegris": { listing:"NASDAQ: ENTG", size:"约 7,000+ 人", commute:"约 40–50 分钟", salary:"约 ¥9–15M" },
  "Intuitive Surgical": { listing:"NASDAQ: ISRG", size:"日本约 355 人", commute:"约 45–55 分钟", salary:"约 ¥10–18M（估算）" },
  "Medtronic": { listing:"NYSE: MDT", size:"约 95,000+ 人（全球）", commute:"待确认", salary:"约 ¥10–17M（估算）" },
  "MicroPort MedBot": { listing:"HKEX: 2252", size:"待确认", commute:"上海岗位", salary:"约 RMB 96–144k（当前专员岗位）" },
  "Zimmer Biomet": { listing:"NYSE: ZBH", size:"约 18,000+ 人（全球）", commute:"取决于地区", salary:"约 ¥10–17M（估算）" },
  "CMR Surgical": { listing:"未上市", size:"待确认", commute:"取决于地区", salary:"待确认" },
  "ECOVACS": { listing:"上交所 603486", size:"约 5,000+ 人（全球）", commute:"海外岗位", salary:"待确认" },
  "BangBang Robotics": { listing:"未上市", size:"待确认", commute:"上海岗位", salary:"约 RMB 300–500k（估算）" },
  "万拿机器人": { listing:"未上市（天使期）", size:"约 20–99 人", commute:"北京岗位", salary:"约 RMB 180–300k" },
  "OMRON": { listing:"东证 Prime 6645", size:"约 28,000+ 人（全球）", commute:"京都约 2 小时+", salary:"约 ¥8–13M（估算）" },
};
export const detailsFor = (candidate: Candidate): CompanyDetail => companyDetails[candidate.company] ?? { listing:"待确认", size:"待确认", commute:"待确认", salary:"约 ¥8–14M（估算）" };

export const existingRadarKeys = new Set([
  "flatiron health|strategic partnerships senior manager", "jmdc|制药业务战略・解决方案 business produce", "syneos health|sr. strategic project manager", "hokuto|solution strategist", "prevent|cso / corporate planning director", "contrea|制药业务负责人", "boehringer ingelheim（人药）|healthcare affairs planning", "coopervision|commercial operations specialist", "alcon|commercial excellence solutions analyst", "boehringer ingelheim animal health|commercial technology & analytics manager", "johnson & johnson medtech|business analytics & market intelligence specialist", "stryker|senior manager, commercial solutions",
]);

export const candidates: Candidate[] = [
  { id:"a-ubie-cs", track:"A", company:"Ubie", title:"カスタマーサクセスマネージャー（病院DX）", href:"https://herp.careers/v1/ubiehr/QLFY7hOWBA1b", source:"公司官网", location:"日本", roleType:"客户采用 / 部署经营", why:"直接连接医疗现场的活用定着与自律运营，符合主线 A 的 HealthTech 采用入口。", gate:"确认是否拥有采用 KPI、产品反馈与合理的现场/工时边界。", verdict:"优先审阅" },
  { id:"a-ubie-alliance", track:"A", company:"Ubie", title:"事業開発（アライアンス）", href:"https://herp.careers/v1/ubiehr/3gAfQex6qWc1", source:"公司官网", location:"日本", roleType:"既有伙伴激活 / 新业务", why:"产品、方案、合作与项目推进兼具，是医疗行业事实和商业化资本的入口。", gate:"核验新伙伴陌生开发占比；需有合同、采用或产品输入，而非关系维护。", verdict:"优先审阅" },
  { id:"a-ubie-newbiz", track:"A", company:"Ubie", title:"事業開発（新規事業責任者候補）", href:"https://herp.careers/v1/ubiehr", source:"公司官网", location:"日本", roleType:"产品商业化 / 新业务经营", why:"面向医疗机构、药企与自治体的产品化和协作，贴近路线图的第二跳能力。", gate:"职级可能偏高；只在职责可拆分、现金与团队质量通过时推进。", verdict:"条件式" },
  { id:"a-ubie-pm", track:"A", company:"Ubie", title:"シニアプロダクトマネージャー（ファーマ）", href:"https://herp.careers/v1/ubiehr", source:"公司官网", location:"日本", roleType:"医疗产品管理", why:"能积累药企、数据产品与产品路线图事实。", gate:"确认不要求成熟 PdM 技术履历；需拥有发布与采用，而不是内部协调。", verdict:"条件式" },
  { id:"a-ubie-account", track:"A", company:"Ubie", title:"Account Sales（病院事業）", href:"https://herp.careers/v1/ubiehr/YqzT_AkpVhBs", source:"公司官网", location:"日本", roleType:"医疗机构解决方案", why:"可直接建立医院工作流和采购证据。", gate:"岗位含销售成分；若个人陌生开发与 quota 是核心则不采用。", verdict:"暂不建议" },
  { id:"a-jmdc-newbiz", track:"A", company:"JMDC", title:"新規事業開発（臨床開発領域DX）", href:"https://herp.careers/careers/companies/jmdc/jobs/h4-cmnvyg74l030p2a0ft7p82p27", source:"公司官网", location:"东京", roleType:"医疗数据新业务", why:"数据、产品、药企/支付方与集团协同，能形成路线图所需行业事实。", gate:"确认有明确产品/客户结果，而不是纯集团战略或 PMI。", verdict:"优先审阅" },
  { id:"a-jmdc-pdm", track:"A", company:"JMDC", title:"プロダクトマネージャー（医药数据工具）", href:"https://herp.careers/careers/companies/jmdc/jobs/h4-cmpla6kwk005d370gbo015edp", source:"公司官网", location:"东京", roleType:"产品 Owner / 客户采用", why:"开发、销售与既有客户之间的产品优先级和活用扩张，符合主线 A 的跳 1。", gate:"确认技术要求可由业务型 Product Owner 覆盖，且拥有 roadmap/发布。", verdict:"优先审阅" },
  { id:"a-jmdc-pm", track:"A", company:"JMDC", title:"シニアプロジェクトマネージャー（新規AIプロダクト）", href:"https://herp.careers/careers/companies/jmdc/jobs/h4-cmn93eqhs031h2o0f1as4tgcj", source:"公司官网", location:"东京", roleType:"AI 产品开发 / 跨职能交付", why:"进入医疗大数据与 AI 产品创造，具备高价值行业门槛。", gate:"避免退化为纯项目管理；要求具备产品发布、采用或业务指标。", verdict:"条件式" },
  { id:"a-jmdc-bizlead", track:"A", company:"JMDC", title:"事業責任者候補（ポストコンサル）", href:"https://herp.careers/careers/companies/jmdc/jobs/h4-cmhdlnro9031ys607s4t59odt", source:"公司官网", location:"东京", roleType:"新业务经营", why:"从策略到 PoC、产品和经营的完整范围，与终局方向相符。", gate:"很可能超出第一跳可达性；只作为拉伸申请或推荐制机会。", verdict:"条件式" },
  { id:"a-hokuto-am", track:"A", company:"HOKUTO", title:"アカウントマネージャー", href:"https://herp.careers/careers/companies/hokuto/jobs/1otFciqrvxVX", source:"公司官网", location:"东京 / 远程", roleType:"药企解决方案 / 客户经营", why:"医疗平台与药企方案能够补充客户、合同和商业化事实。", gate:"公开描述含新客户开拓；仅在既有账户/方案经营为主时采用。", verdict:"条件式" },
  { id:"a-linkedin-pathology-pm", track:"A", company:"病理 AI 企业（职位由 LinkedIn 发布）", title:"AI Product Manager（病理 AI 产品战略）", href:"https://www.linkedin.com/jobs/view/4456779260/", source:"LinkedIn MCP", location:"东京 / 远程", roleType:"医疗 AI 产品战略", why:"LinkedIn 搜索发现的医疗 AI 产品岗位；如果职位范围包含产品战略与实际采用，可补强主线 A 的产品资本。", gate:"先核验实际雇主、产品成熟度、产品 Owner 范围与医疗行业经验要求。", verdict:"条件式" },
  { id:"b-mujin-srpm", track:"B", company:"Mujin", title:"Senior Product Manager", href:"https://jobs.lever.co/mujininc?location=Tokyo%2C+Japan+%28MJHQ%29", source:"公司官网", location:"东京（现场）", roleType:"工业机器人产品管理", why:"全球化工业机器人平台，产品路线图和客户工作流资本强。", gate:"现场办公明显；确认职责覆盖发布与采用，不只是硬件供应链。", verdict:"条件式" },
  { id:"b-mujin-hwpm", track:"B", company:"Mujin", title:"Product Manager, Hardware Lifecycle & Supply Chain", href:"https://jobs.lever.co/mujininc/d1f8be48-c090-4c3f-ab4a-f3efc0c3e701", source:"公司官网", location:"东京（现场）", roleType:"硬件产品管理", why:"能获得机器人硬件、供应链与合规事实，是物理 AI 的可迁移资本。", gate:"岗位偏供应链；若没有客户价值、产品决策或发布所有权则降权。", verdict:"条件式" },
  { id:"b-woven-pm", track:"B", company:"Woven by Toyota", title:"Project Manager, Robot PF Biz & Strategy", href:"https://jobs.lever.co/woven-by-toyota/356811fb-b4e9-4d77-92be-9be288b278ca", source:"公司官网", location:"东京 / 静冈裾野", roleType:"机器人平台商业化", why:"产品、GTM、伙伴、商业模型与 P&L 可同时积累。", gate:"可能转往裾野且现场频繁；不满足东京基地红线时不采用。", verdict:"暂不建议" },
  { id:"b-woven-tpm", track:"B", company:"Woven by Toyota", title:"Technical Product Manager, Robot Platform", href:"https://jobs.lever.co/woven-by-toyota/9d2001ad-7fef-4bd5-8628-40faa6fa31d1", source:"公司官网", location:"东京（混合）", roleType:"机器人产品管理", why:"客户问题到产品化的接口，符合 B 路径 P。", gate:"需要技术深度；先核验是否接受业务型产品/商业化背景。", verdict:"条件式" },
  { id:"b-woven-delivery", track:"B", company:"Woven by Toyota", title:"Project Manager, Robot Delivery Service", href:"https://jobs.lever.co/woven-by-toyota?location=Tokyo", source:"公司官网", location:"东京 / 静冈裾野", roleType:"机器人部署经营", why:"机器人服务上线和采用可形成路线图中路径 D 的证据。", gate:"地点与出差风险同样存在；只在东京长期基地书面确认时考虑。", verdict:"暂不建议" },
  { id:"b-woven-cs", track:"B", company:"Woven by Toyota", title:"Customer Success and Deployment Strategist", href:"https://jobs.lever.co/woven-by-toyota?location=Tokyo", source:"公司官网", location:"东京（混合）", roleType:"实体系统部署 / 客户采用", why:"虽非纯机器人，但属于物理系统部署与客户价值的可迁移入口。", gate:"确认产品化与客户采用占比，避免长期项目协调。", verdict:"条件式" },
  { id:"b-rapyuta-pm", track:"B", company:"Rapyuta Robotics", title:"Product Manager, WMS / ASRS", href:"https://www.rapyuta-robotics.com/careers/", source:"公司官网", location:"东京", roleType:"仓储机器人产品管理", why:"直接对应路径 P：产品、仓储场景、上线与客户 ROI。", gate:"官网职位状态需再次核验；只考虑拥有 roadmap、发布和采用的范围。", verdict:"优先审阅" },
  { id:"b-prox-pm", track:"B", company:"Prox Industries", title:"Physical AI 项目经理", href:"https://herp.careers/v1/prox/1CSDkQXCL-AY", source:"公司官网", location:"日本", roleType:"Physical AI 社会实施", why:"客户现场与技术团队之间的社会实施能力，与实体 AI 主线高度一致。", gate:"JD 对技术背景要求较高且项目制风险大；缺少产品所有权则不采用。", verdict:"条件式" },
  { id:"b-inaho-pm", track:"B", company:"inaho", title:"项目经理（AI机器人共同开发）", href:"https://herp.careers/v1/inaho/QKd05pIorFz_", source:"公司官网", location:"日本", roleType:"AI 机器人共同开发", why:"从现场问题到验证的跨域工作，具备农业机器人和全球化期权。", gate:"高度技术型共同开发；不适合作为无工程履历的第一优先。", verdict:"暂不建议" },
  { id:"b-mi6-pdm", track:"B", company:"MI-6", title:"产品经理（材料 AI / 机器人）", href:"https://herp.careers/careers/companies/misix/jobs/MlxZn4DKlf9d", source:"公司官网", location:"日本", roleType:"研发基础设施产品", why:"将 AI、自动化与实体研发流程连接，具备全球可迁移性。", gate:"与机器人客户部署的距离较远；仅在产品 Owner 范围明确时审阅。", verdict:"条件式" },
  { id:"b-linkedin-entegris", track:"B", company:"Entegris", title:"Regional Product Manager", href:"https://www.linkedin.com/jobs/view/4401545917/", source:"LinkedIn MCP", location:"东京（现场）", roleType:"实体制造产品 / 区域经营", why:"LinkedIn 搜索发现的实体制造产品岗位，包含关键客户、产品改进、跨职能执行与工厂 P&L 议题，是机器人主线的邻接性桥梁。", gate:"非直接机器人；现场办公与制造业经验要求较强，只作条件式桥梁。", verdict:"条件式" },
  {id:"a-intuitive-pmm",track:"A",company:"Intuitive Surgical",title:"Product Marketing Manager（da Vinci）",href:"https://careers.intuitive.com/jp/jobs/744000138823961/JOB216930/product-marketing-manager/",source:"公司官网",location:"东京（现场）",roleType:"手术机器人产品上市 / 本地化",why:"当前职位负责 da Vinci 的日本新品上市、定价、销售预测、本地价值主张与发布后优化，是主线 A 最直接的产品商业化入口。",gate:"要求医疗器械产品营销经验；核验现金、团队层级与是否可将既有 GTM 经验证明为等价能力。",verdict:"优先审阅",scannedOn:"2026-08-23"},
  {id:"a-intuitive-ion-access",track:"A",company:"Intuitive Surgical",title:"Senior Manager, Japan Evidence & Access Strategy – Ion",href:"https://careers.intuitive.com/jp/jobs/744000138825309/JOB215547/senior-manager-japan-evidence-access-strategy-ion/",source:"公司官网",location:"东京（现场）",roleType:"医疗机器人市场准入 / 证据战略",why:"连接临床证据、支付方、市场准入和采用扩张，且覆盖 APAC；与罕见病市场推出经验有高价值的相邻性。",gate:"10 年+ HEOR/医疗器械市场准入及带人要求很高，作为拉伸申请。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"a-medtronic-surgical",track:"A",company:"Medtronic",title:"Senior Product Specialist, Surgical",href:"https://medtronic.wd1.myworkdayjobs.com/medtroniccareers/job/Tokyo-Tokyo-Japan/Senior-Product-Specialist--Surgical---Tokyo-_R70366",source:"公司官网",location:"东京",roleType:"手术平台日本商业化",why:"把全球 Surgical 商业化计划转为日本上市与增长计划，业务组合含机器人辅助手术平台。",gate:"确认该岗位仍开放、是否偏临床器械背景，以及薪资能否达标。",verdict:"优先审阅",scannedOn:"2026-08-23"},
  {id:"a-microport-overseas",track:"A",company:"MicroPort MedBot",title:"海外市场专员",href:"https://www.linkedin.com/jobs/view/4439642517/",source:"LinkedIn MCP",location:"上海",roleType:"手术机器人海外市场 / KOL",why:"海外市场、KOL、学术活动、销售支持与竞争情报，是中国手术机器人国际化的低门槛商业入口。",gate:"公开区间明显低于当前基线且职级偏初级；仅作进入行业或谈更高职级的参考。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"a-zimmer-commercial",track:"A",company:"Zimmer Biomet",title:"Commercial Enablement & Marketing Technology",href:"https://careers.zimmerbiomet.com/us/en/job/10226/Business-Systems-Associate-Director-Commercial-Enablement-Marketing-Technology",source:"公司官网",location:"全球 / 远程视岗位",roleType:"骨科机器人商业卓越",why:"ROSA 机器人平台所在公司已有商业赋能与营销技术职能，是从商业分析切入医疗机器人生态的可迁移路径。",gate:"该具体链接为近期职位证据；先确认当前开放地区及是否接受日本/中国候选人。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"a-cmr-commercial",track:"A",company:"CMR Surgical",title:"Commercial / Customer Success / Medical Affairs",href:"https://us.cmrsurgical.com/job-search",source:"公司官网",location:"英国 / 全球",roleType:"手术机器人商业化与客户采用",why:"Versius 的招聘体系明确覆盖 Commercial、Customer Success 与 Medical Affairs，可建立手术机器人部署和采用资本。",gate:"当前公开岗位的地域以英国和其他市场为主；只在非纯猎手、地点和签证可行时审阅。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-ecovacs-apj",track:"B",company:"ECOVACS",title:"Marketing Supervisor, APJ",href:"https://www.ecovacs.com/sg/careers/job-detail?id=4",source:"公司官网",location:"新加坡",roleType:"服务机器人区域产品上市",why:"当前岗位覆盖产品发布、GTM 协同、市场定位、渠道与线上/线下营销，是家用服务机器人全球化的直接入口。",gate:"确认新加坡工作许可、实际薪资及工作强度；职责偏品牌执行时降权。",verdict:"优先审阅",scannedOn:"2026-08-23"},
  {id:"b-ecovacs-emea",track:"B",company:"ECOVACS",title:"Brand Manager, EMEA",href:"https://www.ecovacs.com/de/careers/job-detail?id=91",source:"公司官网",location:"德国杜塞尔多夫",roleType:"机器人品牌本地化 / 区域上市",why:"跨国本地化、产品发布、零售和电商协同，是从日本/中国走向全球的高迁移性商业化路径。",gate:"需要欧洲工作资格和多国营销经历；作为全球路线的第二跳候选。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-bangbang-gtm",track:"B",company:"BangBang Robotics",title:"GTM（智能辅助出行）",href:"https://www.bangbangrobotics.com/job/236.html",source:"公司官网",location:"上海",roleType:"康复机器人产品 GTM",why:"负责产品全生命周期、上市策略、渠道、量价预测和海外市场，连接医疗/养老与实体智能。",gate:"确认团队节奏、出差频率及可获得的产品商业化所有权；中国现金需满足底线。",verdict:"优先审阅",scannedOn:"2026-08-23"},
  {id:"b-wana-gtm",track:"B",company:"万拿机器人",title:"GTM 经理（具身智能）",href:"https://www.zhaopin.com/jobdetail/CCL1502557420J40894259713.htm",source:"公开招聘平台",location:"北京",roleType:"工业具身智能 GTM",why:"岗位覆盖定位、定价、渠道、销售赋能、上市 readiness 与产品反馈，是最完整的具身智能商业化职能之一。",gate:"天使期团队、高强度与个人结果压力都较高；须核验股权、工时和现金补偿。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-omron-pmm",track:"B",company:"OMRON",title:"AMR / Cobot 产品营销（日本市场）",href:"https://job.axol.jp/qd/c/omron/public/job/detail/0zr5YAPeRlJGnF-hg",source:"公司官网",location:"京都",roleType:"工业机器人产品市场展开",why:"当前岗位将 AMR/Cobot 的客户场景、销售策略、伙伴协同和产品改进闭环，是主线 B 的优质非工程入口。",gate:"需补足机器人/FA 技术理解；京都现已在可接受地点范围内。",verdict:"优先审阅",scannedOn:"2026-08-23"},
  {id:"b-unitree-global-market",track:"B",company:"Unitree Robotics",title:"海外市场 / 全球渠道",href:"https://www.unitree.com/about/",source:"公司官网",location:"杭州 / 全球",roleType:"人形与足式机器人全球商业化",why:"消费级与行业级足式/人形机器人兼具，全球销售与渠道业务是中日能力的高迁移入口。",gate:"官网需确认具体开放职位；避免纯代理销售或要求深度技术售前的范围。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-unitree-application",track:"B",company:"Unitree Robotics",title:"产品应用 / 行业解决方案",href:"https://www.unitree.com/about/",source:"公司官网",location:"杭州 / 全球",roleType:"机器人场景产品化",why:"连接客户场景、产品能力与全球落地，是从 GTM 转入具身智能真实部署的桥梁。",gate:"仅在岗位有产品/客户成功所有权而非纯技术支持时采用。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-softbank-pm",track:"B",company:"SoftBank Robotics",title:"Product Marketing / Product Manager",href:"https://www.softbankrobotics.com/careers/",source:"公司官网",location:"东京 / 全球",roleType:"服务机器人产品商业化",why:"服务机器人公司通常需要产品定位、合作伙伴、行业方案与上线采用，商业化背景可直接迁移。",gate:"先核验当前开放职位、产品线稳定性与个人 quota 占比。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-softbank-cs",track:"B",company:"SoftBank Robotics",title:"Customer Success / Deployment",href:"https://www.softbankrobotics.com/careers/",source:"公司官网",location:"东京 / 全球",roleType:"服务机器人部署采用",why:"机器人上线、客户价值证明和产品反馈是实体 AI 的核心护城河。",gate:"确认不是高频现场救火或纯项目协调，且具备合理的远程/现场边界。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-telexistence-bd",track:"B",company:"Telexistence",title:"Business Development / Partnerships",href:"https://www.telexistence.com/careers",source:"公司官网",location:"东京",roleType:"远程操作机器人商业化",why:"零售机器人从方案、伙伴到部署的商业化路径，适合补足实体系统 GTM 资本。",gate:"核验商业模式、公司资金跑道、出差和个人销售目标。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-telexistence-pm",track:"B",company:"Telexistence",title:"Product Manager / Deployment Strategy",href:"https://www.telexistence.com/careers",source:"公司官网",location:"东京",roleType:"机器人产品与规模部署",why:"在客户工作流和产品路线图之间建立闭环，是主线 B 的直接产品化入口。",gate:"官网需核验开放性；需确认岗位不要求工程背景或全天候现场支持。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-preferred-bd",track:"B",company:"Preferred Robotics",title:"Business Development / 事業開発",href:"https://www.preferred-robotics.jp/recruit/",source:"公司官网",location:"东京",roleType:"机器人产品事業开发",why:"以研究型机器人技术走向客户和产业合作的路径，能补足 AI 到实体产品的商业化经验。",gate:"确认是否为真实产品商业化范围，而非研究合作募资或纯销售。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-preferred-pm",track:"B",company:"Preferred Robotics",title:"Product Manager / Product Planning",href:"https://www.preferred-robotics.jp/recruit/",source:"公司官网",location:"东京",roleType:"机器人产品规划",why:"将客户需求、产品定义和 AI/机器人技术团队连接，是长期进入 physical AI 的好跳板。",gate:"须确认开放岗位与经验要求，避免只面向深度机器人研发履历。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-ascent-bd",track:"B",company:"Ascent Robotics",title:"Business Development / Strategic Partnerships",href:"https://www.ascent.ai/careers",source:"公司官网",location:"东京",roleType:"自主移动系统伙伴商业化",why:"自主系统的伙伴、客户场景和市场进入可形成具身 AI 商业化证据。",gate:"先确认日本实体岗位与业务成熟度；不接受以陌生开发 quota 为核心的版本。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-ascent-cs",track:"B",company:"Ascent Robotics",title:"Customer Success / Program Manager",href:"https://www.ascent.ai/careers",source:"公司官网",location:"东京",roleType:"自主系统部署采用",why:"部署、采用和客户反馈闭环是低技术门槛但高壁垒的物理 AI 入口。",gate:"核验在招状态、现场比例以及是否有明确客户成果指标。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-terra-bd",track:"B",company:"Terra Drone",title:"Business Development（无人机 / 机器人）",href:"https://terra-drone.net/recruit/",source:"公司官网",location:"东京 / 全球",roleType:"空中机器人业务开发",why:"无人机是具身智能的可迁移分支；全球项目、监管和场景商业化都能建立稀缺资本。",gate:"确认不是重 sales quota 或高频长期出差，及岗位对海外驻在的要求。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-terra-pm",track:"B",company:"Terra Drone",title:"Product Manager / 新规事業",href:"https://terra-drone.net/recruit/",source:"公司官网",location:"东京 / 全球",roleType:"无人机产品商业化",why:"将飞行数据、监管、客户工作流和产品路线图结合，是 B 主线的相邻产品岗位。",gate:"官网需核验职位开放性；优先具备产品发布而非纯项目交付的范围。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-sensyn-bd",track:"B",company:"SENSYN ROBOTICS",title:"Business Development / 事業開発",href:"https://www.sensyn-robotics.com/recruit/",source:"公司官网",location:"东京",roleType:"自治体与基础设施机器人商业化",why:"无人机、机器人和社会基础设施的客户场景可形成高壁垒的部署/GTM经验。",gate:"公共部门周期和出差可能较重；确认销售结构不是纯 hunter。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-sensyn-pm",track:"B",company:"SENSYN ROBOTICS",title:"Product Manager / Solution Marketing",href:"https://www.sensyn-robotics.com/recruit/",source:"公司官网",location:"东京",roleType:"机器人解决方案产品化",why:"用客户任务定义产品和服务、再回传数据与需求，是实体 AI 的优质产品入口。",gate:"优先能拥有产品采用/收入 KPI 的岗位，回避纯投标文档角色。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-denso-planning",track:"B",company:"DENSO",title:"Robotics Business Planning / Product Planning",href:"https://careers.denso.com/",source:"公司官网",location:"爱知 / 东京 / 全球",roleType:"工业机器人业务战略",why:"大型制造平台可提供机器人产品、全球供应链和客户场景的长期行业资本。",gate:"日本地点仅限东京/京都/大阪才作为当前候选；确认职能不退化为内部报告。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-denso-market",track:"B",company:"DENSO",title:"Global Product Marketing / Market Development",href:"https://careers.denso.com/",source:"公司官网",location:"全球",roleType:"自动化产品全球市场进入",why:"全球制造与产品市场进入经验可迁移到机器人平台和智能硬件。",gate:"优先日本/中国/可行海外地点，且需避开长期驻厂或纯汽车 OEM 销售。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-yaskawa-global",track:"B",company:"Yaskawa Electric",title:"Robotics Global Marketing / Overseas Business",href:"https://www.yaskawa-global.com/recruit",source:"公司官网",location:"福冈 / 东京 / 全球",roleType:"工业机器人全球市场",why:"全球工业机器人龙头的海外市场、产品与渠道岗位有强产业迁移性。",gate:"福冈非当前居住优先；仅在东京/京都/大阪或明确海外机会时进入深审。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-yaskawa-pm",track:"B",company:"Yaskawa Electric",title:"Robotics Product Planning",href:"https://www.yaskawa-global.com/recruit",source:"公司官网",location:"福冈 / 东京 / 全球",roleType:"工业机器人产品规划",why:"产品定义、伙伴生态和客户应用有助于获得物理 AI 产业事实。",gate:"技术门槛可能高；验证能否以 GTM/产品经营而非控制工程背景切入。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-kawasaki-biz",track:"B",company:"Kawasaki Heavy Industries",title:"Robotics Business Planning / Market Development",href:"https://www.khi.co.jp/recruit/",source:"公司官网",location:"东京 / 兵库 / 全球",roleType:"机器人业务经营",why:"工业/医疗相关机器人业务中的市场进入、伙伴与产品经营是可迁移的商业化资本。",gate:"兵库不在当前日本地点范围；确认东京/海外配置、职级及工时。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-kawasaki-pm",track:"B",company:"Kawasaki Heavy Industries",title:"Robotics Product Marketing",href:"https://www.khi.co.jp/recruit/",source:"公司官网",location:"东京 / 兵库 / 全球",roleType:"机器人产品市场展开",why:"机器人产品上市与客户应用扩展能建立 B 主线所需的行业和采用资本。",gate:"只审阅拥有市场/产品结果的岗位，排除纯工程或长期驻厂版本。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-fanuc-market",track:"B",company:"FANUC",title:"Global Marketing / Business Development",href:"https://www.fanuc.co.jp/en/recruit/",source:"公司官网",location:"山梨 / 东京 / 全球",roleType:"工业机器人全球商业化",why:"全球机器人龙头的海外客户、渠道与产品市场经验具有极强的行业护城河。",gate:"山梨不是常规可接受地点；仅审阅东京、海外或可远程的配置。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-fanuc-pm",track:"B",company:"FANUC",title:"Robot Product Planning / Solution Business",href:"https://www.fanuc.co.jp/en/recruit/",source:"公司官网",location:"山梨 / 东京 / 全球",roleType:"工业机器人产品经营",why:"从客户自动化场景反推产品和解决方案，有利于建立产品化与 P&L 资本。",gate:"先确认职位开放、办公地与技术背景要求；不为品牌接受地点或工时失配。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-dobot-overseas",track:"B",company:"DOBOT",title:"Overseas Market / Channel Development",href:"https://www.dobot-robots.com/career.html",source:"公司官网",location:"深圳 / 全球",roleType:"协作机器人海外市场",why:"协作机器人出海需要本地化、渠道、产品定位和客户应用，是中日/全球迁移性很强的入口。",gate:"确认现金、海外出差与个人销售目标；优先区域 GTM 而非纯经销商开拓。",verdict:"条件式",scannedOn:"2026-08-23"},
  {id:"b-dobot-pmm",track:"B",company:"DOBOT",title:"Product Marketing Manager（协作机器人）",href:"https://www.dobot-robots.com/career.html",source:"公司官网",location:"深圳 / 全球",roleType:"协作机器人产品上市",why:"机器人产品定位、场景化卖点和全球发布是与 Anker GTM 类似、但更贴近 B 主线的路径。",gate:"官网需核验实际岗位；确认不要求深度控制/自动化工程履历。",verdict:"条件式",scannedOn:"2026-08-23"},
];
